apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd
  template:
    metadata:
      labels:
        app: ci-cd
    spec:
      containers:
        - name: ci-cd
          imagePullPolicy: Always
          image: minwu1234/ci-cd:latest
          ports:
            - containerPort: 8080
