apiVersion: v1
kind: Service
metadata:
  name: ci-cd
spec:
  type: NodePort
  selector:
    app: ci-cd
  ports:
    - protocol: TCP
      port: 8080         # Cluster 내부 포트
      targetPort: 8080   # 컨테이너 포트
      nodePort: 30080    # EC2에서 노출될 포트 (30000~32767 사이)
